export interface GlossarySeed {
  term: string;
  definition: string;
  extended?: string;
  category: string;
  related?: string[];
}

export const GLOSSARY_SEEDS: GlossarySeed[] = [
  { term: 'Address', definition: 'A unique identifier (derived from a public key) that represents a wallet on a blockchain and can receive funds.', extended: 'Addresses are shareable openly — like an account number or IBAN. On Ethereum they start with 0x, on Bitcoin they commonly start with 1, 3 or bc1.', category: 'General', related: ['Public Key', 'Wallet'] },
  { term: 'Airdrop', definition: 'Free distribution of tokens to wallet addresses, usually to promote a project or reward early users.', extended: 'Airdrops are also a common scam vector — never enter your seed phrase to "claim" tokens.', category: 'General', related: ['Token', 'DYOR'] },
  { term: 'Altcoin', definition: 'Any cryptocurrency other than Bitcoin; "alternative coin".', category: 'General', related: ['Bitcoin', 'Memecoin'] },
  { term: 'Atomic Swap', definition: 'A trustless exchange of two different cryptocurrencies directly between parties without an intermediary.', category: 'Technology', related: ['Smart Contract', 'DEX'] },
  { term: 'Bear Market', definition: 'A prolonged period of falling prices, typically defined as a 20%+ decline from recent highs.', category: 'Trading', related: ['Bull Market', 'FUD'] },
  { term: 'Block', definition: 'A batch of validated transactions appended to a blockchain, referenced by the blocks before and after it.', category: 'Technology', related: ['Blockchain', 'Nonce'] },
  { term: 'Blockchain', definition: 'A distributed, append-only ledger maintained by a peer-to-peer network using cryptography and consensus rules.', category: 'Technology', related: ['Block', 'Consensus'] },
  { term: 'Bull Market', definition: 'A sustained period of rising prices and optimistic sentiment.', category: 'Trading', related: ['Bear Market', 'FOMO'] },
  { term: 'Burn', definition: 'Permanently removing tokens from circulation by sending them to an unspendable address.', extended: 'Burning reduces circulating supply, often to support price or as a fee mechanism (e.g. EIP-1559 base-fee burn).', category: 'General', related: ['Token', 'Supply'] },
  { term: 'Cold Wallet', definition: 'A wallet whose private keys are stored offline, isolated from internet-connected devices.', extended: 'Includes hardware wallets (Ledger, Trezor) and paper/steel backups. Best practice for long-term holdings.', category: 'Security', related: ['Hot Wallet', 'Seed Phrase'] },
  { term: 'Consensus', definition: 'The rules by which a decentralized network agrees on a single version of the ledger.', extended: 'Major mechanisms: Proof of Work (Bitcoin) and Proof of Stake (Ethereum post-Merge).', category: 'Technology', related: ['Proof of Work', 'Proof of Stake'] },
  { term: 'DAO', definition: 'Decentralized Autonomous Organization — an entity governed by token holders voting on-chain.', category: 'DeFi', related: ['Smart Contract', 'Governance'] },
  { term: 'DApp', definition: 'Decentralized application — a frontend that talks to smart contracts instead of a company server.', category: 'Technology', related: ['Smart Contract', 'Web3'] },
  { term: 'DeFi', definition: 'Decentralized Finance — financial services (lending, trading, insurance) built on public blockchains without intermediaries.', extended: 'Key primitives: AMMs, lending markets, CDPs, and staking protocols. TVL is the sector\'s headline metric.', category: 'DeFi', related: ['AMM', 'TVL', 'Yield Farming'] },
  { term: 'DEX', definition: 'Decentralized exchange — a smart-contract-based exchange where trades settle on-chain and users keep custody.', category: 'DeFi', related: ['AMM', 'Liquidity'] },
  { term: 'DYOR', definition: '"Do Your Own Research" — a reminder that nobody bears your losses but you.', category: 'General', related: ['FOMO', 'Rug Pull'] },
  { term: 'ERC-20', definition: 'The token standard that defines a common interface for fungible tokens on Ethereum and EVM chains.', category: 'Technology', related: ['Smart Contract', 'Token'] },
  { term: 'Faucet', definition: 'A website that dispenses small amounts of cryptocurrency for free, usually in exchange for completing captchas or tasks.', extended: 'Faucets were originally created to distribute testnet coins, then became a popular onboarding tool for mainnet coins. See our Faucets page for curated listings.', category: 'General', related: ['Testnet', 'Wallet'] },
  { term: 'Fiat', definition: 'Government-issued currency (USD, EUR, JPY) not backed by a physical commodity.', category: 'General', related: ['Stablecoin', 'On-Ramp'] },
  { term: 'FOMO', definition: '"Fear Of Missing Out" — buying an asset because it is rising, without analysis.', category: 'Trading', related: ['Bull Market', 'HODL'] },
  { term: 'Fork', definition: 'A change to a protocol\'s rules. Soft forks are backward compatible; hard forks create a divergent chain.', extended: 'Bitcoin Cash (2017) and Ethereum Classic (2016) are famous hard forks.', category: 'Technology', related: ['Blockchain'] },
  { term: 'FUD', definition: '"Fear, Uncertainty, Doubt" — negative information (or disinformation) that pressures prices.', category: 'Trading', related: ['Bear Market'] },
  { term: 'Gas', definition: 'The unit measuring computational work in a transaction; gas × gas price = the fee paid to validators.', extended: 'On Ethereum, gas prices are denominated in gwei (1 gwei = 0.000000001 ETH). Use our Gas Tracker tool for live prices.', category: 'Technology', related: ['Gwei', 'Wallet'] },
  { term: 'Gwei', definition: 'A denomination of ETH equal to one-billionth of an ether (10^-9), used to quote gas prices.', category: 'Technology', related: ['Gas'] },
  { term: 'Halving', definition: 'The programmed 50% reduction in Bitcoin\'s block reward roughly every four years.', extended: 'See our full article: "Bitcoin Halving Explained".', category: 'Mining', related: ['Proof of Work', 'Hash Rate'] },
  { term: 'Hash Rate', definition: 'The total computational power dedicated to mining a proof-of-work network — a proxy for network security.', category: 'Mining', related: ['Difficulty', 'Proof of Work'] },
  { term: 'HODL', definition: 'A famous 2013 typo of "hold" that became slang for holding through volatility.', category: 'Trading', related: ['FOMO'] },
  { term: 'Hot Wallet', definition: 'A wallet connected to the internet (browser or mobile) — convenient but more attack surface.', category: 'Security', related: ['Cold Wallet', 'Seed Phrase'] },
  { term: 'KYC', definition: '"Know Your Customer" — identity verification required by regulated exchanges and service providers.', category: 'Security', related: ['AML'] },
  { term: 'Liquidity', definition: 'How easily an asset can be bought or sold without moving its price; deeper books = more liquidity.', category: 'Trading', related: ['AMM', 'Slippage'] },
  { term: 'Mainnet', definition: 'A project\'s production blockchain with real economic value, as opposed to a testnet.', category: 'Technology', related: ['Testnet', 'Faucet'] },
  { term: 'Memecoin', definition: 'A cryptocurrency whose value derives from internet culture and community rather than technology.', extended: 'DOGECOIN and SHIB are the archetypes. Extremely high risk.', category: 'General', related: ['Altcoin', 'FOMO'] },
  { term: 'Mining', definition: 'The process of validating transactions and securing a proof-of-work blockchain in exchange for block rewards.', category: 'Mining', related: ['Hash Rate', 'Proof of Work'] },
  { term: 'NFT', definition: 'Non-Fungible Token — a unique, indivisible token representing ownership of a specific asset.', category: 'General', related: ['Token', 'ERC-20'] },
  { term: 'Node', definition: 'A computer running a blockchain\'s software that validates and relays transactions.', category: 'Technology', related: ['Blockchain'] },
  { term: 'Nonce', definition: 'A one-time random value. In mining, the number miners iterate to find a valid block; in wallet login, a server-generated challenge proving signature freshness.', category: 'Technology', related: ['Block', 'Wallet'] },
  { term: 'Private Key', definition: 'The secret cryptographic credential that controls a wallet. Whoever holds it controls the funds.', extended: 'Never share it. Any site or person asking for your private key or seed phrase is scamming you.', category: 'Security', related: ['Seed Phrase', 'Public Key'] },
  { term: 'Proof of Stake', definition: 'Consensus where validators lock collateral (stake) and are rewarded for honest attestation.', category: 'Technology', related: ['Staking', 'Consensus'] },
  { term: 'Proof of Work', definition: 'Consensus where miners expend energy solving hash puzzles to add blocks.', category: 'Technology', related: ['Mining', 'Hash Rate'] },
  { term: 'Public Key', definition: 'The non-secret half of a keypair; addresses are derived from it.', category: 'Technology', related: ['Private Key', 'Address'] },
  { term: 'Rug Pull', definition: 'A scam where a project team drains liquidity or abandons a token after attracting deposits.', category: 'Security', related: ['DYOR', 'Liquidity'] },
  { term: 'SATS', definition: 'The smallest unit of Bitcoin: 1 satoshi = 0.00000001 BTC, named after the pseudonymous creator.', category: 'General', related: ['Bitcoin'] },
  { term: 'Seed Phrase', definition: 'A 12–24 word mnemonic that encodes a wallet\'s private keys — the master backup.', extended: 'Write it on paper or steel, store it in separate secure locations, and never digitize it.', category: 'Security', related: ['Cold Wallet', 'Private Key'] },
  { term: 'Slippage', definition: 'The difference between expected and executed price when an order exceeds available liquidity.', category: 'Trading', related: ['Liquidity'] },
  { term: 'Smart Contract', definition: 'Self-executing code deployed on a blockchain that enforces agreed rules without intermediaries.', category: 'Technology', related: ['DApp', 'DeFi'] },
  { term: 'Stablecoin', definition: 'A token pegged to a stable asset, usually the US dollar (USDT, USDC, DAI).', category: 'DeFi', related: ['Fiat', 'DeFi'] },
  { term: 'Staking', definition: 'Locking tokens to secure a proof-of-stake network (or delegate to a validator) and earning rewards.', category: 'DeFi', related: ['Proof of Stake', 'Liquid Staking'] },
  { term: 'Liquid Staking', definition: 'Staking via a protocol that returns a tradable token (e.g. stETH) representing the staked position plus accrued rewards.', category: 'DeFi', related: ['Staking'] },
  { term: 'Testnet', definition: 'A parallel blockchain using valueless coins for testing applications and features.', category: 'Technology', related: ['Mainnet', 'Faucet'] },
  { term: 'Token', definition: 'A digital asset issued on top of an existing blockchain (as opposed to a chain\'s native coin).', category: 'General', related: ['ERC-20', 'Coin'] },
  { term: 'TVL', definition: 'Total Value Locked — the aggregate capital deposited in a DeFi protocol; the sector\'s headline size metric.', category: 'DeFi', related: ['DeFi', 'Yield Farming'] },
  { term: 'Wallet', definition: 'Software or hardware that manages private keys and lets users sign transactions.', category: 'General', related: ['Cold Wallet', 'Hot Wallet'] },
  { term: 'Web3', definition: 'The vision of an internet where users own their data, identity, and assets via blockchains.', category: 'General', related: ['DApp', 'Wallet'] },
  { term: 'Whale', definition: 'An entity holding enough of an asset to move markets with its trades.', category: 'Trading', related: ['Liquidity'] },
  { term: 'Whitepaper', definition: 'The founding technical document describing a project\'s problem, design, and tokenomics.', category: 'General', related: ['DYOR'] },
  { term: 'Yield Farming', definition: 'Deploying assets across DeFi protocols to earn fees, interest, or incentive tokens.', category: 'DeFi', related: ['DeFi', 'AMM', 'TVL'] },
  { term: 'AMM', definition: 'Automated Market Maker — a smart contract that prices trades against a liquidity pool formula (e.g. x·y=k) rather than an order book.', category: 'DeFi', related: ['DEX', 'Liquidity'] },
  { term: 'Difficulty', definition: 'A network-adjusted parameter controlling how hard the mining puzzle is, targeting a constant block time.', category: 'Mining', related: ['Hash Rate'] },
];
